swagger: "2.0"
info:
  version: "0.0.1"
  title: "SNIB API"
host: localhost:8080
basePath: /snib
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /getGridIds:
    get:
      description: Response los `id` de las celdas del mapa
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    gridid:
                      type: integer
  
  /getSpecie:
    get:
      description: |
        Regresa un conjunto especies filtrado por `nom_sp` o algunas si no
        existe filtro
      parameters: 
        -
          name: nom_sp
          in: query
          description: Palabra de búsqueda para el nombre de una especie
          type: string
        -
          name: limit
          in: query
          description: Número de resultados que quiere que se despliegen
          type: number
          default: 20
      responses:
        "200":
          description: Success
          schema: 
            type: object
            properties: 
              data:
                type: array
                items: 
                  type: object
                  properties:
                    nom_sp:
                      type: string
                    spid:
                      type: integer
                    reinovalido:
                      type: string
                    phylumdivisionvalido:
                      type: string
                    clasevalida: 
                      type: string
                    ordenvalida:
                      type: string
                    familiavalida:
                      type: string
                    generovalido:
                      type: string
                    epitetovalido:
                      type: string
          examples:
            application/json:
              data:
                - 
                  nom_sp: Holocentrus rufus
                  spid: 53196
                  reinovalido: Animalia
                  phylumdivisionvalido: Craniata
                  clasevalida: Actinopterygii
                  ordenvalido: Beryciformes
                  familiavalida: Holocentridae
                  generovalido: Holocentrus
                  epitetovalido: rufus
                - 
                  nom_sp: Molossus rufus
                  spid: 49311
                  reinovalido: Animalia
                  phylumdivisionvalido: Craniata
                  clasevalida: Mammalia
                  ordenvalido: Chiroptera
                  familiavalida: Molossidae
                  generovalido: Molossus
                  epitetovalido: rufus
    post:
      description: |
        Regresa un conjunto especies filtrado por `nom_sp` o algunas si no
        existe filtro
      parameters:
        -
          name: payload
          in: body
          schema:
            type: object 
            properties:
              nom_sp:
                type: string
              limit:
                type: number
                default: 20
      responses:
        "200":
          description: Success
          schema: 
            type: object
            properties: 
              data:
                type: array
                items: 
                  type: object
                  properties:
                    nom_sp:
                      type: string
                    spid:
                      type: integer
                    reinovalido:
                      type: string
                    phylumdivisionvalido:
                      type: string
                    clasevalida: 
                      type: string
                    ordenvalida:
                      type: string
                    familiavalida:
                      type: string
                    generovalido:
                      type: string
                    epitetovalido:
                      type: string
          examples:
            application/json:
              data:
                - 
                  nom_sp: Holocentrus rufus
                  spid: 53196
                  reinovalido: Animalia
                  phylumdivisionvalido: Craniata
                  clasevalida: Actinopterygii
                  ordenvalido: Beryciformes
                  familiavalida: Holocentridae
                  generovalido: Holocentrus
                  epitetovalido: rufus
                - 
                  nom_sp: Molossus rufus
                  spid: 49311
                  reinovalido: Animalia
                  phylumdivisionvalido: Craniata
                  clasevalida: Mammalia
                  ordenvalido: Chiroptera
                  familiavalida: Molossidae
                  generovalido: Molossus
                  epitetovalido: rufus
  /getSpecie/{id}:
    get:
      parameters:
        -
          name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: Lorem Ipsum Dolot ...
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object

          